# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  - master

pool:
  vmImage: ubuntu-latest

steps:
  - task: JavaToolInstaller@0
    displayName: 'Use Java 17'
    inputs:
      versionSpec: 17
      jdkArchitectureOption: x64
      jdkSourceOption: PreInstalled
  - task: CmdLine@2
    displayName: 'Maven Build Spark'
    inputs:
      script: './build/mvn -Drepo.login=$(repoUsername) -Drepo.pwd=$(repoPassword) -Dtarget=17 -Djava.version=17  -Pscala-2.13 -DskipTests clean deploy --settings settings.xml'
